intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

./: lib{art-unicode}: libul{art-unicode}

libul{art-unicode}: {hxx ixx txx cxx}{** -**.test... -version} \
                     {hxx            }{                version}

libul{art-unicode}: $impl_libs $intf_libs

# Unit tests.
#
exe{*.test}:
{
  test = true
  install = false
}

test_libs =
import test_libs =+ libart-validation%lib{art-validation}

for t: cxx{**.test...}
{
  d = $directory($t)
  n = $name($t)...

  ./: $d/exe{$n}: $t $d/{hxx ixx txx}{+$n} $d/testscript{+$n} $test_libs
  $d/exe{$n}: libul{art-unicode}: bin.whole = false
}

hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{art-unicode}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{art-unicode}: bin.lib.version = "-$version.project_id"
else
  lib{art-unicode}: bin.lib.version = "-$version.major.$version.minor"

# Install into the art/unicode/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/art/unicode/
  install.subdirs = true
}
